### ISSUE TITLE
Carrry over from Feb Milestone

### ISSUE THREAD

**Issue by zsthampi** [zsthampi/SE17-Group-N#10]
- [ ] Book a domain and host the website
- [ ] Add data for all the courses on the website 
- [ ] Enhance text mining solution to rate specific Professor
